# Usar a imagem oficial do PostgreSQL
FROM postgres:latest

# Definir variáveis de ambiente para o usuário, senha e nome do banco de dados
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_DB=loja

EXPOSE 5432


CMD ["postgres"]

