services:
  banco:
    container_name: loja-banco
    hostname: loja-banco
    env_file:
      - ./.env
    ports:
      - ${POSTGREE_PORTA}:5432
    build:
      context: ./banco
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - loja

  api:
    container_name: loja-api
    hostname: loja-api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - ${API_PORTA}:80
    networks:
      - loja
    tty: true

  arquivos:
    container_name: loja-arquivos
    hostname: loja-arquivos
    build:
      context: ./arquivos
      dockerfile: Dockerfile
    ports:
      - ${ARQUIVOS_PORTA}:80
    volumes:
      - ./arquivos:/app
    networks:
      - loja
    tty: true

  auth:
    container_name: loja-auth
    hostname: loja-auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - ${AUTH_PORTA}:80
    volumes:
      - ./auth:/app
    networks:
      - loja
    tty: true
#
#  pagamento:
#    image: NODE
#    hostname: loja-pagamentos
#    ports:
#      - ${PAGAMENTOS_PORTA}:${PAGAMENTOS_PORTA}
#    volumes:
#      - ./pagamentos:/pagamentos
#    networks:
#      - loja
#    tty: true
#
#  frontend:
#    image: NODE
#    hostname: loja-frontend
#    volumes:
#      - ./frontend:/app
#    networks:
#      - loja
#    tty: true

networks:
  loja:
    driver: bridge
