version: '3.8'
services:
  banco:
    env_file:
      - ./.env
    container_name: loja-banco
    hostname: loja-banco
    ports:
      - ${POSTGREE_PORTA}:${POSTEGREE_PORTA}
    build:
      context: ./banco
      dockerfile: Dockerfile
    volumes:
      - ./banco/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: unless-stopped
    networks:
      - loja

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - loja
    tty: true

  arquivos:
    image: NGINX
    ports:
      - 80:80
      - 442:442
    hostname: loja-arquivos
    volumes:
      - ./arquivos:/arquivos
    networks:
      - loja
    tty: true


  pagamento:
    image: NODE
    hostname: loja-pagamentos
    ports:
      - ${PAGAMENTOS_PORTA}:${PAGAMENTOS_PORTA}
    volumes:
      - ./pagamentos:/pagamentos
    networks:
      - loja
    tty: true

  frontend:
    image: NODE
    hostname: loja-frontend
    volumes:
      - ./frontend:/app
    networks:
      - loja
    tty: true

networks:
  loja:
    driver: bridge
